# Generated by Django 6.0.2 on 2026-03-03 00:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BatteryPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('capacity', models.CharField(max_length=50)),
                ('transaction_type', models.CharField(choices=[('hire', 'Hire'), ('sale', 'Sale')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hire_duration', models.CharField(blank=True, help_text='e.g., per day, per week', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('set_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BatteryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('vehicle_plate', models.CharField(blank=True, max_length=10)),
                ('transaction_type', models.CharField(choices=[('hire', 'Hire'), ('sale', 'Sale'), ('return', 'Return')], max_length=10)),
                ('battery_brand', models.CharField(max_length=100)),
                ('battery_capacity', models.CharField(max_length=50)),
                ('quantity', models.IntegerField(default=1)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hire_start', models.DateField(blank=True, null=True)),
                ('hire_end', models.DateField(blank=True, null=True)),
                ('transaction_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('receipt_number', models.CharField(max_length=20, unique=True)),
                ('notes', models.TextField(blank=True)),
                ('served_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TyrePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('set_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TyreServiceTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_plate', models.CharField(max_length=10)),
                ('driver_name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('service_type', models.CharField(choices=[('pressure', 'Pressure Check'), ('puncture', 'Puncture Fixing'), ('valve', 'Valve Replacement'), ('new_tyre', 'New Tyre Sale')], max_length=20)),
                ('tyre_size', models.CharField(blank=True, max_length=50)),
                ('tyre_brand', models.CharField(blank=True, max_length=100)),
                ('quantity', models.IntegerField(default=1)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('receipt_number', models.CharField(max_length=20, unique=True)),
                ('notes', models.TextField(blank=True)),
                ('served_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'System Admin'), ('attendant', 'Parking Attendant'), ('tyre_manager', 'Tyre Section Manager'), ('battery_manager', 'Battery Section Manager')], default='attendant', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('nin_number', models.CharField(blank=True, max_length=30)),
                ('vehicle_type', models.CharField(choices=[('truck', 'Truck'), ('personal_car', 'Personal Car'), ('taxi', 'Taxi'), ('coaster', 'Coaster'), ('boda_boda', 'Boda-boda')], max_length=20)),
                ('number_plate', models.CharField(max_length=10)),
                ('vehicle_model', models.CharField(max_length=100)),
                ('vehicle_color', models.CharField(max_length=50)),
                ('arrival_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('departure_time', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('registered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_vehicles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ParkingReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(max_length=20, unique=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('receiver_name', models.CharField(blank=True, max_length=100)),
                ('receiver_phone', models.CharField(blank=True, max_length=20)),
                ('receiver_gender', models.CharField(blank=True, max_length=10)),
                ('receiver_nin', models.CharField(blank=True, max_length=30)),
                ('signed_out_at', models.DateTimeField(blank=True, null=True)),
                ('signed_out_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='core.vehicle')),
            ],
        ),
    ]
